// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_pmf_zanim
double log_pmf_zanim(std::vector<int> x, std::vector<double> prob, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanim(SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim(x, prob, zeta));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanim_vec
std::vector<double> log_pmf_zanim_vec(int n, int d, std::vector<int> x, std::vector<double> prob, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanim_vec(SEXP nSEXP, SEXP dSEXP, SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim_vec(n, d, x, prob, zeta));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanim_approx
double log_pmf_zanim_approx(std::vector<int> x, std::vector<double> prob, std::vector<double> zeta, double scale, int mc, int nskip);
RcppExport SEXP _zanicc_log_pmf_zanim_approx(SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP, SEXP scaleSEXP, SEXP mcSEXP, SEXP nskipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type mc(mcSEXP);
    Rcpp::traits::input_parameter< int >::type nskip(nskipSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim_approx(x, prob, zeta, scale, mc, nskip));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanidm
double log_pmf_zanidm(std::vector<int> x, std::vector<double> alpha, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanidm(SEXP xSEXP, SEXP alphaSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanidm(x, alpha, zeta));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
double rtnorm(const double& mean, const double& sd, const double& a);
RcppExport SEXP _zanicc_rtnorm(SEXP meanSEXP, SEXP sdSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const double& >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(mean, sd, a));
    return rcpp_result_gen;
END_RCPP
}
// compute_crps
arma::vec compute_crps(const arma::mat& samples, const arma::vec& truth, const int& n_samps);
RcppExport SEXP _zanicc_compute_crps(SEXP samplesSEXP, SEXP truthSEXP, SEXP n_sampsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_samps(n_sampsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_crps(samples, truth, n_samps));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_multinomial_bart();
RcppExport SEXP _rcpp_module_boot_probit_bart();
RcppExport SEXP _rcpp_module_boot_zanidm_linear_reg();
RcppExport SEXP _rcpp_module_boot_zanim_bart_probit();
RcppExport SEXP _rcpp_module_boot_zanim_lognormal_bart();
RcppExport SEXP _rcpp_module_boot_zanim_linear_reg();

static const R_CallMethodDef CallEntries[] = {
    {"_zanicc_log_pmf_zanim", (DL_FUNC) &_zanicc_log_pmf_zanim, 3},
    {"_zanicc_log_pmf_zanim_vec", (DL_FUNC) &_zanicc_log_pmf_zanim_vec, 5},
    {"_zanicc_log_pmf_zanim_approx", (DL_FUNC) &_zanicc_log_pmf_zanim_approx, 6},
    {"_zanicc_log_pmf_zanidm", (DL_FUNC) &_zanicc_log_pmf_zanidm, 3},
    {"_zanicc_rtnorm", (DL_FUNC) &_zanicc_rtnorm, 3},
    {"_zanicc_compute_crps", (DL_FUNC) &_zanicc_compute_crps, 3},
    {"_rcpp_module_boot_multinomial_bart", (DL_FUNC) &_rcpp_module_boot_multinomial_bart, 0},
    {"_rcpp_module_boot_probit_bart", (DL_FUNC) &_rcpp_module_boot_probit_bart, 0},
    {"_rcpp_module_boot_zanidm_linear_reg", (DL_FUNC) &_rcpp_module_boot_zanidm_linear_reg, 0},
    {"_rcpp_module_boot_zanim_bart_probit", (DL_FUNC) &_rcpp_module_boot_zanim_bart_probit, 0},
    {"_rcpp_module_boot_zanim_lognormal_bart", (DL_FUNC) &_rcpp_module_boot_zanim_lognormal_bart, 0},
    {"_rcpp_module_boot_zanim_linear_reg", (DL_FUNC) &_rcpp_module_boot_zanim_linear_reg, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_zanicc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
