// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// log_pmf_zanim
double log_pmf_zanim(std::vector<int> x, std::vector<double> prob, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanim(SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim(x, prob, zeta));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanim_vec
std::vector<double> log_pmf_zanim_vec(int n, int d, std::vector<int> x, std::vector<double> prob, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanim_vec(SEXP nSEXP, SEXP dSEXP, SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim_vec(n, d, x, prob, zeta));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanim_approx
double log_pmf_zanim_approx(std::vector<int> x, std::vector<double> prob, std::vector<double> zeta, double scale, int mc, int nskip);
RcppExport SEXP _zanicc_log_pmf_zanim_approx(SEXP xSEXP, SEXP probSEXP, SEXP zetaSEXP, SEXP scaleSEXP, SEXP mcSEXP, SEXP nskipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type prob(probSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type mc(mcSEXP);
    Rcpp::traits::input_parameter< int >::type nskip(nskipSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanim_approx(x, prob, zeta, scale, mc, nskip));
    return rcpp_result_gen;
END_RCPP
}
// log_pmf_zanidm
double log_pmf_zanidm(std::vector<int> x, std::vector<double> alpha, std::vector<double> zeta);
RcppExport SEXP _zanicc_log_pmf_zanidm(SEXP xSEXP, SEXP alphaSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_pmf_zanidm(x, alpha, zeta));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm
double rtnorm(const double& mean, const double& sd, const double& a);
RcppExport SEXP _zanicc_rtnorm(SEXP meanSEXP, SEXP sdSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const double& >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm(mean, sd, a));
    return rcpp_result_gen;
END_RCPP
}
// rmvnorm_chol_22
std::vector<double> rmvnorm_chol_22(const std::vector<double>& mean, const std::vector<double>& L, int p);
RcppExport SEXP _zanicc_rmvnorm_chol_22(SEXP meanSEXP, SEXP LSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm_chol_22(mean, L, p));
    return rcpp_result_gen;
END_RCPP
}
// rmvnorm_chol_33
std::vector<double> rmvnorm_chol_33(std::vector<double>& mean, arma::mat Sigma, int p);
RcppExport SEXP _zanicc_rmvnorm_chol_33(SEXP meanSEXP, SEXP SigmaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm_chol_33(mean, Sigma, p));
    return rcpp_result_gen;
END_RCPP
}
// mat_to_double_rowmajor
std::vector<double> mat_to_double_rowmajor(const arma::mat& X);
RcppExport SEXP _zanicc_mat_to_double_rowmajor(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_to_double_rowmajor(X));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_dm_linear_reg();
RcppExport SEXP _rcpp_module_boot_inverse_posterior();
RcppExport SEXP _rcpp_module_boot_multinomial_bart();
RcppExport SEXP _rcpp_module_boot_multinomial_lognormal_bart();
RcppExport SEXP _rcpp_module_boot_multinomial_shared_bart();
RcppExport SEXP _rcpp_module_boot_probit_bart();
RcppExport SEXP _rcpp_module_boot_shared_logit_bart();
RcppExport SEXP _rcpp_module_boot_zanidm_linear_reg();
RcppExport SEXP _rcpp_module_boot_zanim_bart_logit();
RcppExport SEXP _rcpp_module_boot_zanim_bart_probit();
RcppExport SEXP _rcpp_module_boot_zanim_ln_bart();
RcppExport SEXP _rcpp_module_boot_zanim_ln_reg();
RcppExport SEXP _rcpp_module_boot_zanim_linear_reg();
RcppExport SEXP _rcpp_module_boot_zanim_shared_bart_probit();

static const R_CallMethodDef CallEntries[] = {
    {"_zanicc_log_pmf_zanim", (DL_FUNC) &_zanicc_log_pmf_zanim, 3},
    {"_zanicc_log_pmf_zanim_vec", (DL_FUNC) &_zanicc_log_pmf_zanim_vec, 5},
    {"_zanicc_log_pmf_zanim_approx", (DL_FUNC) &_zanicc_log_pmf_zanim_approx, 6},
    {"_zanicc_log_pmf_zanidm", (DL_FUNC) &_zanicc_log_pmf_zanidm, 3},
    {"_zanicc_rtnorm", (DL_FUNC) &_zanicc_rtnorm, 3},
    {"_zanicc_rmvnorm_chol_22", (DL_FUNC) &_zanicc_rmvnorm_chol_22, 3},
    {"_zanicc_rmvnorm_chol_33", (DL_FUNC) &_zanicc_rmvnorm_chol_33, 3},
    {"_zanicc_mat_to_double_rowmajor", (DL_FUNC) &_zanicc_mat_to_double_rowmajor, 1},
    {"_rcpp_module_boot_dm_linear_reg", (DL_FUNC) &_rcpp_module_boot_dm_linear_reg, 0},
    {"_rcpp_module_boot_inverse_posterior", (DL_FUNC) &_rcpp_module_boot_inverse_posterior, 0},
    {"_rcpp_module_boot_multinomial_bart", (DL_FUNC) &_rcpp_module_boot_multinomial_bart, 0},
    {"_rcpp_module_boot_multinomial_lognormal_bart", (DL_FUNC) &_rcpp_module_boot_multinomial_lognormal_bart, 0},
    {"_rcpp_module_boot_multinomial_shared_bart", (DL_FUNC) &_rcpp_module_boot_multinomial_shared_bart, 0},
    {"_rcpp_module_boot_probit_bart", (DL_FUNC) &_rcpp_module_boot_probit_bart, 0},
    {"_rcpp_module_boot_shared_logit_bart", (DL_FUNC) &_rcpp_module_boot_shared_logit_bart, 0},
    {"_rcpp_module_boot_zanidm_linear_reg", (DL_FUNC) &_rcpp_module_boot_zanidm_linear_reg, 0},
    {"_rcpp_module_boot_zanim_bart_logit", (DL_FUNC) &_rcpp_module_boot_zanim_bart_logit, 0},
    {"_rcpp_module_boot_zanim_bart_probit", (DL_FUNC) &_rcpp_module_boot_zanim_bart_probit, 0},
    {"_rcpp_module_boot_zanim_ln_bart", (DL_FUNC) &_rcpp_module_boot_zanim_ln_bart, 0},
    {"_rcpp_module_boot_zanim_ln_reg", (DL_FUNC) &_rcpp_module_boot_zanim_ln_reg, 0},
    {"_rcpp_module_boot_zanim_linear_reg", (DL_FUNC) &_rcpp_module_boot_zanim_linear_reg, 0},
    {"_rcpp_module_boot_zanim_shared_bart_probit", (DL_FUNC) &_rcpp_module_boot_zanim_shared_bart_probit, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_zanicc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
