#' Compute simplex volumes
#'
#' Compute a quantity proportional to the volume of one or more simplices.
#'
#' @param i An integer matrix with \eqn{p+1} columns indicating the simplices.
#' Each row contains the row indices of the vertices defining a simplex in `X`.
#' @param X A numeric \eqn{n \times p} matrix representing a set of points in
#' \eqn{\mathbb{R}^p}. Each row corresponds to one point and each column to one
#' coordinate.
#'
#' @details
#' For each simplex, the function computes the determinant of the matrix formed by
#' subtracting the first vertex from the remaining \eqn{p} vertices. The absolute
#' value of this determinant is proportional to the simplex volume.
#'
#' @return A numeric vector containing one value per simplex.
.volume_simplices <- function(i, X) {
  if (!is.matrix(i)) i <- matrix(i, nrow = 1)
  apply(i, 1, function(j) {
    S <- X[j, ]
    X0 <- apply(S[-1, ], 1, `-`, y = S[1, ])
    det(X0)
  })
}

#' Generate uniform random points from the the convex hull of set of points
#'
#' Generate random points uniformly distributed over the convex hull of a set of
#' points in Euclidean space.
#'
#' @param n Integer giving the number of points to generate.
#' @param X A numeric \eqn{n \times p} matrix representing a set of points in
#' \eqn{\mathbb{R}^p}. Each row is a point and each column is a coordinate.
#'
#' @details
#' The function samples uniformly from the convex hull of the points in `X`.
#' The algorithm proceeds as follows:
#' \enumerate{
#'   \item The convex hull is partitioned into non-overlapping simplices using
#'   the Delaunay triangulation computed by [geometry::delaunayn()].
#'
#'   \item The volume of each simplex is computed. A simplex is selected with
#'   probability proportional to its volume.
#'
#'   \item A point is sampled uniformly within the selected simplex:
#'   \itemize{
#'     \item Uniform barycentric coordinates are generated by sampling from a
#'     Dirichlet distribution with parameters
#'     \eqn{(1,\ldots,1)}. This is implemented by normalising independent
#'     exponential random variables.
#'     \item The barycentric coordinates are transformed into Cartesian
#'     coordinates using the vertices of the selected simplex.
#'   }
#' }
#'
#' This implementation follows the method described by Stack Exchange user  **whuber**:
#' <https://stats.stackexchange.com/questions/663559/transform-convex-hull-vertex-weights-for-uniform-distribution/663594#663594>.
#'
#' @return
#' A numeric \eqn{n \times p} matrix containing independent samples uniformly
#' distributed over the convex hull of the points in `X`.
#'
#' @export
runifconvexhull <- function(n, X) {
  # Triangulate the points. Indexes into simplices, by row.
  V <- geometry::delaunayn(X, options = "Qt")
  p_dim <- ncol(V) - 1 #ncol(X) #
  k_simplices <- nrow(V)
  # Sample the component simplices of the triangulation proportional to their volumes
  probs <- abs(.volume_simplices(V, X))
  probs <- probs / sum(probs)
  ind <- sample.int(k_simplices, n, replace = TRUE, prob = probs)
  # Now, sample uniformly within each selected simplex, that is, Dir(1,...,1)
  wts <- matrix(stats::rexp(n * (p_dim + 1)), nrow = n)
  wts <- wts / rowSums(wts)
  # Apply the weights to obtain Cartesian point coordinates
  pts <- sapply(seq_len(n), function(j) wts[j, ] %*% X[V[ind[j], ], ])
  t(pts)
}



#' @name inverse_posterior
#'
#' @title Sample from the inverse posterior distribution of past climate variables
#'
#' @description
#' Approximates the inverse posterior distribution of the unobserved climate
#' variables given the corresponding with compositional fossil counts, and the
#' posterior draws of parameters from the ZANIM-LN-BART model.
#'
#' This is the main quantity of interest when performing pollen-based palaeoclimate
#' reconstruction using the ZANIM-LN-BART model.
#'
#'
#' @param object A fitted ZANIM-LN-BART model of class `zanicc`. The model must
#' have been fitted using a modern calibration data set.
#' @param Y A matrix of fossil count-compositional observations with samples in
#' rows and taxa in columns. The taxa (columns) must match those used in the modern
#' data set.
#' @param method Character string specifying the sampling algorithm. One of
#' `"sir"` (the default), `"ess"`, or `"cess"`.
#' @param dir_posterior_fx Directory used by the `"sir"` method to store (or
#' retrieve) the taxon-specific posterior tree ensembles required for likelihood
#' evaluation.
#' @param x_proposal Proposal samples used by the `"sir"` method. Each row
#' corresponds to a proposed climate vector.
#' @param ndpost Number of posterior draws from the fitted ZANIM-LN-BART model
#' to use. Must not exceed `object$ndpost`.
#' @param nburnin Number of burn-in iterations for the `"ess"` and `"cess"`
#' methods. For each posterior draw of the forward model, the ESS/cESS sampler
#' is run for `nburnin` iterations before collecting a sample. The default
#' (`nburnin = 1`) corresponds to the naive cut-posterior algorithm.
#' @param n_particles Number of particles, that is, samples used to obtain an unbiased estimate of
#' the ZANIM-LN-BART likelihood.
#' @param mean_prior,S_prior Prior mean vector and covariance matrix, respectively,
#' for the climate variables used for the `ess` and `cess` methods.
#' @param X_ini Initial climate values used to initialise the ESS/CESS samplers. The default is `NULL`,
#' which then uses a sample from the prior.
#' @param Amat,bvec H-representation of the convex hull.
#' @param lower,upper Integers giving the lower and upper limits to constrain the
#' past climate.
#' @param eta Tuning parameter using in the `cess` algorithm related to the logistic
#' approximation of the indicator function. Defaults to `50.0`.
#'
#' @details
#'
#' This function implements the Bayesian modular framework proposed in
#' in Menezes et al. (2026) to perform palaeoclimate reconstruction.
#'
#' The function performs inverse prediction using a previously fitted
#' ZANIM-LN-BART model.
#' The ZANIM-LN-BART model is first fitted to a modern
#' calibration data set in order to estimate the pollen-climate relationships
#'
#' Given one or more fossil assemblages, this function uses
#' these posterior draws to approximate the cut posterior distribution of the
#' corresponding latent climate variables.
#'
#' Several sampling algorithms are available, including sampling-importance-
#' resampling (SIR), elliptical slice sampling (ESS), and constrained
#' elliptical slice sampling (CESS).
#'
#' This function is a high-level interface to an efficient `C++` implementation.
#'
#' @rdname inverse_posterior
#' @export
inverse_posterior_zanimlnbart <- function(object, Y,
                                          method = c("sir", "ess", "cess"),
                                          dir_posterior_fx = NULL,
                                          x_proposal = NULL,
                                          ndpost = object$ndpost, nburnin = 1L,
                                          n_particles = NULL,
                                          mean_prior = NULL,
                                          S_prior = NULL,
                                          X_ini = NULL,
                                          Amat = NULL, bvec = NULL,
                                          lower = NULL, upper = NULL,
                                          eta = 50.0) {

  # Some checks
  method <- match.arg(method)
  if (is.null(n_particles)) n_particles <- if (method == "sir") 1L else  100L
  if (object$d != ncol(Y)) stop("Dimension of Y does not match with forward model")
  if (ndpost > object$ndpost) {
    warning("{ndpost} should be at least {object$ndpost}. Setting {ndpost} to  {object$ndpost}")
    ndpost <- object$ndpost
  }
  if (method == "sir" && is.null(x_proposal)) stop("You should give the {x_proposal} for sir!")

  # Some common arguments
  B <- t(object$Bt)
  n <- nrow(Y)
  p <- object$p_theta

  # Initialise C++ class
  ml <- Rcpp::Module(module = "inverse_posterior", PACKAGE = "zanicc")
  cpp_obj <- new(ml$InversePosterior, object$d, object$ntrees_theta,
                 object$ntrees_zeta, object$forests_dir)

  # Check which method to dispatch
  if (method == "sir") {
    n_proposal <- nrow(x_proposal)
    # Check if the files with parameter predictions exist
    ftheta <- file.path(dir_posterior_fx, "theta_ij.bin")
    fzeta <- file.path(dir_posterior_fx, "zeta_ij.bin")
    do_predict <- FALSE
    if (!file.exists(ftheta) || !file.exists(fzeta)) {
      do_predict <- TRUE
      cat("files {theta_ij.bin} and {zeta_ij.bin} with the posterior distribution of f^{(c)}(x*) and f^{(0)}(x*) do not exist in the folder {dir_posterior_fx}. Computing such predictions...\n")
      # Compute the posterior distribution of f^{(c)}_j(x*) and f^{(0)}_j(x*) for x*~\pi(x*) and j=1,...,d
      ini <- proc.time()
      predict(object, newdata = x_proposal, load = FALSE, output_dir = dir_posterior_fx,
              type = "theta")
      predict(object, newdata = x_proposal, load = FALSE, output_dir = dir_posterior_fx,
              type = "zeta")
      end_predict <- proc.time() - ini
    }
    # Run SIR
    ini <- proc.time()
    cpp_obj$SIR(Y, n_proposal, ndpost, B, dir_posterior_fx)
    elapsed <- proc.time() - ini
    # Copy posterior into array
    idx_sir <- cpp_obj$indices_sir + 1L
    res <- array(dim = c(ndpost, p, n))
    for (i in seq_len(n)) {
      indices <- idx_sir[(1 + ndpost*(i - 1L)):(ndpost*i)]
      res[,,i] <- x_proposal[indices, ]
    }
    res <- simplify2array(res)
    # save effective sample size
    attr(res, "effsize") <- matrix(cpp_obj$ess_sir, nrow = ndpost)
    if (do_predict) attr(res, "elapsed_time_predict") <- end_predict
  } else if (method %in% c("ess", "cess")) {

    if (is.null(mean_prior)) mean_prior <- rep(0.0, object$p_theta)
    if (is.null(S_prior)) S_prior <- diag(1.0, object$p_theta, object$p_theta)

    if (p == 1) {
      ini <- proc.time()
      xx <- switch(method,
                   "ess" = {
                     if (is.null(X_ini)) X_ini <- stats::rnorm(n = n, mean = mean_prior, sd = S_prior)
                     cpp_obj$ESS1p(Y, X_ini, ndpost, nburnin, n_particles,
                                   mean_prior, S_prior, B)
                   },
                   "cess" = {
                     if (is.null(X_ini)) X_ini <- truncnorm::rtruncnorm(n = n, a = lower, b = upper,
                                                                        mean = mean_prior, sd = S_prior)
                     cpp_obj$CESS1p(Y, X_ini, ndpost, nburnin, n_particles,
                                    mean_prior, S_prior, B, lower, upper, eta)
                   }
      )
      elapsed <- proc.time() - ini
    }
    else {
      # If there is no initial value sample from the prior
      if (is.null(X_ini)) {
        X_ini <- matrix(nrow = n, ncol = p)
        cS <- chol(S_prior)
        for (i in seq_len(n)) X_ini[i, ] <- drop(stats::rnorm(p) %*% cS + mean_prior)
      }

      ini <- proc.time()
      xx <- switch(method,
        "ess" = cpp_obj$ESS(Y, X_ini, ndpost, nburnin, n_particles,
                            mean_prior, S_prior, B),
        "cess" = cpp_obj$CESS(Y, X_ini, ndpost, nburnin, n_particles,
                              mean_prior, S_prior, B, Amat, bvec, eta)
      )
      elapsed <- proc.time() - ini
    }
    # Appending into an array for consistency
    res <- array(xx, dim = c(ndpost, p, n))
  }
  attr(res, "elapsed_time") <- elapsed
  res
}
