# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_pmf_zanim <- function(x, prob, zeta) {
    .Call(`_zanicc_log_pmf_zanim`, x, prob, zeta)
}

log_pmf_zanim_vec <- function(n, d, x, prob, zeta) {
    .Call(`_zanicc_log_pmf_zanim_vec`, n, d, x, prob, zeta)
}

.log_pmf_zanim_approx <- function(x, prob, zeta, scale, mc, nskip) {
    .Call(`_zanicc_log_pmf_zanim_approx`, x, prob, zeta, scale, mc, nskip)
}

log_pmf_zanidm <- function(x, alpha, zeta) {
    .Call(`_zanicc_log_pmf_zanidm`, x, alpha, zeta)
}

.logIlc <- function(x, mu, A, b, eta) {
    .Call(`_zanicc_log_I_lc`, x, mu, A, b, eta)
}

rtnorm <- function(mean, sd, a) {
    .Call(`_zanicc_rtnorm`, mean, sd, a)
}

mat_to_double_rowmajor <- function(X) {
    .Call(`_zanicc_mat_to_double_rowmajor`, X)
}

